import "./globals.css";
import { Header } from "@/components";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FilterProvider } from "@/contexts/FilterContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <FilterProvider>
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </FilterProvider>
    </html>
  );
}
